package com.huadin.earthwire.Model.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.huadin.earthwire.Model.dao.bean.EarthWire;
import com.huadin.earthwire.Model.dao.bean.Person;
import com.huadin.earthwire.Model.dao.bean.Project;
import com.huadin.earthwire.Model.dao.bean.ProjectTeam;

import com.huadin.earthwire.Model.dao.EarthWireDao;
import com.huadin.earthwire.Model.dao.PersonDao;
import com.huadin.earthwire.Model.dao.ProjectDao;
import com.huadin.earthwire.Model.dao.ProjectTeamDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig earthWireDaoConfig;
    private final DaoConfig personDaoConfig;
    private final DaoConfig projectDaoConfig;
    private final DaoConfig projectTeamDaoConfig;

    private final EarthWireDao earthWireDao;
    private final PersonDao personDao;
    private final ProjectDao projectDao;
    private final ProjectTeamDao projectTeamDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        earthWireDaoConfig = daoConfigMap.get(EarthWireDao.class).clone();
        earthWireDaoConfig.initIdentityScope(type);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        projectDaoConfig = daoConfigMap.get(ProjectDao.class).clone();
        projectDaoConfig.initIdentityScope(type);

        projectTeamDaoConfig = daoConfigMap.get(ProjectTeamDao.class).clone();
        projectTeamDaoConfig.initIdentityScope(type);

        earthWireDao = new EarthWireDao(earthWireDaoConfig, this);
        personDao = new PersonDao(personDaoConfig, this);
        projectDao = new ProjectDao(projectDaoConfig, this);
        projectTeamDao = new ProjectTeamDao(projectTeamDaoConfig, this);

        registerDao(EarthWire.class, earthWireDao);
        registerDao(Person.class, personDao);
        registerDao(Project.class, projectDao);
        registerDao(ProjectTeam.class, projectTeamDao);
    }
    
    public void clear() {
        earthWireDaoConfig.getIdentityScope().clear();
        personDaoConfig.getIdentityScope().clear();
        projectDaoConfig.getIdentityScope().clear();
        projectTeamDaoConfig.getIdentityScope().clear();
    }

    public EarthWireDao getEarthWireDao() {
        return earthWireDao;
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public ProjectDao getProjectDao() {
        return projectDao;
    }

    public ProjectTeamDao getProjectTeamDao() {
        return projectTeamDao;
    }

}
