package com.huadin.earthwire.Model.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.huadin.earthwire.Model.dao.bean.ProjectTeam;
import com.huadin.earthwire.Model.dao.bean.WorkName;

import com.huadin.earthwire.Model.dao.ProjectTeamDao;
import com.huadin.earthwire.Model.dao.WorkNameDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig projectTeamDaoConfig;
    private final DaoConfig workNameDaoConfig;

    private final ProjectTeamDao projectTeamDao;
    private final WorkNameDao workNameDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        projectTeamDaoConfig = daoConfigMap.get(ProjectTeamDao.class).clone();
        projectTeamDaoConfig.initIdentityScope(type);

        workNameDaoConfig = daoConfigMap.get(WorkNameDao.class).clone();
        workNameDaoConfig.initIdentityScope(type);

        projectTeamDao = new ProjectTeamDao(projectTeamDaoConfig, this);
        workNameDao = new WorkNameDao(workNameDaoConfig, this);

        registerDao(ProjectTeam.class, projectTeamDao);
        registerDao(WorkName.class, workNameDao);
    }
    
    public void clear() {
        projectTeamDaoConfig.getIdentityScope().clear();
        workNameDaoConfig.getIdentityScope().clear();
    }

    public ProjectTeamDao getProjectTeamDao() {
        return projectTeamDao;
    }

    public WorkNameDao getWorkNameDao() {
        return workNameDao;
    }

}
