package com.huadin.earthwire.Model.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.huadin.earthwire.Model.dao.bean.ProjectTeam;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PROJECT_TEAM".
*/
public class ProjectTeamDao extends AbstractDao<ProjectTeam, Long> {

    public static final String TABLENAME = "PROJECT_TEAM";

    /**
     * Properties of entity ProjectTeam.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Member = new Property(1, String.class, "member", false, "MEMBER");
        public final static Property ProjectName = new Property(2, String.class, "projectName", false, "PROJECT_NAME");
        public final static Property MemberPhone = new Property(3, String.class, "memberPhone", false, "MEMBER_PHONE");
    };


    public ProjectTeamDao(DaoConfig config) {
        super(config);
    }
    
    public ProjectTeamDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PROJECT_TEAM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"MEMBER\" TEXT," + // 1: member
                "\"PROJECT_NAME\" TEXT," + // 2: projectName
                "\"MEMBER_PHONE\" TEXT);"); // 3: memberPhone
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PROJECT_TEAM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ProjectTeam entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String member = entity.getMember();
        if (member != null) {
            stmt.bindString(2, member);
        }
 
        String projectName = entity.getProjectName();
        if (projectName != null) {
            stmt.bindString(3, projectName);
        }
 
        String memberPhone = entity.getMemberPhone();
        if (memberPhone != null) {
            stmt.bindString(4, memberPhone);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ProjectTeam entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String member = entity.getMember();
        if (member != null) {
            stmt.bindString(2, member);
        }
 
        String projectName = entity.getProjectName();
        if (projectName != null) {
            stmt.bindString(3, projectName);
        }
 
        String memberPhone = entity.getMemberPhone();
        if (memberPhone != null) {
            stmt.bindString(4, memberPhone);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ProjectTeam readEntity(Cursor cursor, int offset) {
        ProjectTeam entity = new ProjectTeam( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // member
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // projectName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // memberPhone
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ProjectTeam entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMember(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setProjectName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMemberPhone(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ProjectTeam entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ProjectTeam entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
